In [85]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
df=pd.read_excel("2.xlsx",header=None)

In [86]:
X=df[[13,2,9,55,66,67,10]].iloc[:][1:]

In [87]:
y=df[82].iloc[:][1:]

In [88]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 

In [89]:
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
x_train.columns=[0,1,2,3,4,5,6]
n=x_train.count()[0]
x_train.head()

0    1    2    3    4    5    6
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  1.0  1.0  7.0  5.0
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [90]:
sum_x1=0
sum_x2=0
sum_x3=0
sum_x4=0
sum_x5=0
sum_x6=0
sum_x7=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x1x3=0
sum_x1x4=0
sum_x1x5=0
sum_x1x6=0
sum_x1x7=0
sum_x2x2=0
sum_x2x3=0
sum_x2x4=0
sum_x2x5=0
sum_x2x6=0
sum_x2x7=0
sum_x3x3=0
sum_x3x4=0
sum_x3x5=0
sum_x3x6=0
sum_x3x7=0
sum_x4x4=0
sum_x4x5=0
sum_x4x6=0
sum_x4x7=0
sum_x5x5=0
sum_x5x6=0
sum_x5x7=0
sum_x6x6=0
sum_x6x7=0
sum_x7x7=0
sum_x1y1=0
sum_x2y1=0
sum_x3y1=0
sum_x4y1=0
sum_x5y1=0
sum_x6y1=0
sum_x7y1=0

for i in range(0,n):
    sum_x1=sum_x1+x_train[0][i]
    sum_x2=sum_x2+x_train[1][i]
    sum_x3=sum_x3+x_train[2][i]
    sum_x4=sum_x4+x_train[3][i]
    sum_x5=sum_x5+x_train[4][i]
    sum_x6=sum_x6+x_train[5][i]
    sum_x7=sum_x7+x_train[6][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train[0][i]*x_train[0][i]
    sum_x1x2=sum_x1x2+x_train[0][i]*x_train[1][i]
    sum_x1x3=sum_x1x3+x_train[0][i]*x_train[2][i]
    sum_x1x4=sum_x1x4+x_train[0][i]*x_train[3][i]
    sum_x1x5=sum_x1x5+x_train[0][i]*x_train[4][i]
    sum_x1x6=sum_x1x6+x_train[0][i]*x_train[5][i]
    sum_x1x7=sum_x1x7+x_train[0][i]*x_train[6][i]
    sum_x2x2=sum_x2x2+x_train[1][i]*x_train[1][i]
    sum_x2x3=sum_x2x3+x_train[1][i]*x_train[2][i]
    sum_x2x4=sum_x2x4+x_train[1][i]*x_train[3][i]
    sum_x2x5=sum_x2x5+x_train[1][i]*x_train[4][i]
    sum_x2x6=sum_x2x6+x_train[1][i]*x_train[5][i]
    sum_x2x7=sum_x2x7+x_train[1][i]*x_train[6][i]
    sum_x3x3=sum_x3x3+x_train[2][i]*x_train[2][i]
    sum_x3x4=sum_x3x4+x_train[2][i]*x_train[3][i]
    sum_x3x5=sum_x3x5+x_train[2][i]*x_train[4][i]
    sum_x3x6=sum_x3x6+x_train[2][i]*x_train[5][i]
    sum_x3x7=sum_x3x7+x_train[2][i]*x_train[6][i]
    sum_x4x4=sum_x4x4+x_train[3][i]*x_train[3][i]
    sum_x4x5=sum_x4x5+x_train[3][i]*x_train[4][i]
    sum_x4x6=sum_x4x6+x_train[3][i]*x_train[5][i]
    sum_x4x7=sum_x4x7+x_train[3][i]*x_train[6][i]
    sum_x5x5=sum_x5x5+x_train[4][i]*x_train[4][i]
    sum_x5x6=sum_x5x6+x_train[4][i]*x_train[5][i]
    sum_x5x7=sum_x5x7+x_train[4][i]*x_train[6][i]
    sum_x6x6=sum_x6x6+x_train[5][i]*x_train[5][i]
    sum_x6x7=sum_x6x7+x_train[5][i]*x_train[6][i]
    sum_x7x7=sum_x7x7+x_train[6][i]*x_train[6][i]
    sum_x1y1=sum_x1y1+x_train[0][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train[1][i]*y_train[i]
    sum_x3y1=sum_x3y1+x_train[2][i]*y_train[i]
    sum_x4y1=sum_x4y1+x_train[3][i]*y_train[i]
    sum_x5y1=sum_x5y1+x_train[4][i]*y_train[i]
    sum_x6y1=sum_x6y1+x_train[5][i]*y_train[i]
    sum_x7y1=sum_x7y1+x_train[6][i]*y_train[i]

In [91]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train, y_train)

In [92]:
reg.coef_

array([ 5.97367187e-03, -2.25942420e-03,  1.10948269e-02,  1.13995959e-04,
       -9.48172747e-05,  2.07305537e-05, -9.02176035e-04])

In [93]:
reg.intercept_

0.0015683268687002889

In [94]:
A = np.array([[n, sum_x1, sum_x2,sum_x3,sum_x4,sum_x5,sum_x6,sum_x7], 
              [sum_x1,sum_x1x1,sum_x1x2,sum_x1x3,sum_x1x4,sum_x1x5,sum_x1x6,sum_x1x7],
              [sum_x2,sum_x1x2,sum_x2x2,sum_x2x3,sum_x2x4,sum_x2x5,sum_x2x6,sum_x2x7],
              [sum_x3,sum_x1x3,sum_x2x3,sum_x3x3,sum_x3x4,sum_x3x5,sum_x3x6,sum_x3x7],
              [sum_x4,sum_x1x4,sum_x2x4,sum_x3x4,sum_x4x4,sum_x4x5,sum_x4x6,sum_x4x7],
              [sum_x5,sum_x1x5,sum_x2x5,sum_x3x5,sum_x4x5,sum_x5x5,sum_x5x6,sum_x5x7],
              [sum_x6,sum_x1x6,sum_x2x6,sum_x3x6,sum_x4x6,sum_x5x6,sum_x6x6,sum_x6x7],
              [sum_x7,sum_x1x7,sum_x2x7,sum_x3x7,sum_x4x7,sum_x5x7,sum_x6x7,sum_x7x7]])

In [95]:
B=np.array([sum_y1, sum_x1y1, sum_x2y1,sum_x3y1,sum_x4y1,sum_x5y1,sum_x6y1,sum_x7y1])

In [96]:
from numpy.linalg import inv
Inverse=inv(A)
Inverse

array([[ 2.67960977e-03, -1.09989587e-04,  1.45309908e-04,
        -9.26917317e-04,  2.02152384e-05,  3.15454503e-05,
        -5.46752190e-06, -2.13227086e-05],
       [-1.09989587e-04,  9.39721677e-03, -8.94691504e-03,
        -3.78231751e-04, -3.30596869e-06, -5.45575550e-06,
        -6.24564534e-07,  3.56551153e-05],
       [ 1.45309908e-04, -8.94691504e-03,  8.76733801e-03,
         7.47045913e-04,  7.78267598e-06,  1.95609015e-06,
         1.13057912e-06, -8.76490132e-05],
       [-9.26917317e-04, -3.78231751e-04,  7.47045913e-04,
         4.14773098e-03, -1.40007698e-05, -6.22709466e-05,
         8.98753250e-06, -2.21781437e-04],
       [ 2.02152384e-05, -3.30596869e-06,  7.78267598e-06,
        -1.40007698e-05,  2.11403897e-05, -2.28883880e-06,
         8.08466735e-08, -9.34064009e-06],
       [ 3.15454503e-05, -5.45575550e-06,  1.95609015e-06,
        -6.22709466e-05, -2.28883880e-06,  5.75041392e-06,
        -7.64349347e-07,  2.40847792e-06],
       [-5.46752190e-06, -6.245645

In [97]:
np.around(Inverse @ A).astype(int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [98]:
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]+Inverse[0][3]*B[3]+Inverse[0][4]*B[4]+Inverse[0][5]*B[5]+Inverse[0][6]*B[6]+Inverse[0][7]*B[7]

In [99]:
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]+Inverse[1][3]*B[3]+Inverse[1][4]*B[4]+Inverse[1][5]*B[5]+Inverse[1][6]*B[6]+Inverse[1][7]*B[7]

In [100]:
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]+Inverse[2][3]*B[3]+Inverse[2][4]*B[4]+Inverse[2][5]*B[5]+Inverse[2][6]*B[6]+Inverse[2][7]*B[7]

In [101]:
w3=Inverse[3][0]*B[0]+Inverse[3][1]*B[1]+Inverse[3][2]*B[2]+Inverse[3][3]*B[3]+Inverse[3][4]*B[4]+Inverse[3][5]*B[5]+Inverse[3][6]*B[6]+Inverse[3][7]*B[7]

In [102]:
w4=Inverse[4][0]*B[0]+Inverse[4][1]*B[1]+Inverse[4][2]*B[2]+Inverse[4][3]*B[3]+Inverse[4][4]*B[4]+Inverse[4][5]*B[5]+Inverse[4][6]*B[6]+Inverse[4][7]*B[7]

In [103]:
w5=Inverse[5][0]*B[0]+Inverse[5][1]*B[1]+Inverse[5][2]*B[2]+Inverse[5][3]*B[3]+Inverse[5][4]*B[4]+Inverse[5][5]*B[5]+Inverse[5][6]*B[6]+Inverse[5][7]*B[7]

In [104]:
w6=Inverse[6][0]*B[0]+Inverse[6][1]*B[1]+Inverse[6][2]*B[2]+Inverse[6][3]*B[3]+Inverse[6][4]*B[4]+Inverse[6][5]*B[5]+Inverse[6][6]*B[6]+Inverse[6][7]*B[7]

In [105]:
w7=Inverse[7][0]*B[0]+Inverse[7][1]*B[1]+Inverse[7][2]*B[2]+Inverse[7][3]*B[3]+Inverse[7][4]*B[4]+Inverse[7][5]*B[5]+Inverse[7][6]*B[6]+Inverse[7][7]*B[7]

In [106]:
W=np.array([w0,w1,w2,w3,w4,w5,w6,w7])

In [107]:
W

array([ 1.56832687e-03,  5.97367187e-03, -2.25942420e-03,  1.10948269e-02,
        1.13995959e-04, -9.48172747e-05,  2.07305537e-05, -9.02176035e-04])

In [108]:
x_test.columns=[0,1,2,3,4,5,6]
x_test.head()

0     1    2     3      4       5      6
0  0.00  0.00  0.0  0.00   0.00    0.00   0.00
1  2.18  2.18  1.0  5.87  14.42  157.66  21.71
2  0.00  0.00  0.0  0.00   0.00    0.00   0.00
3  0.00  0.00  0.0  0.00   0.00    0.00   0.00
4  0.00  0.00  0.0  0.00   0.00    0.00   0.00

In [109]:
y_pred=w0+x_test[0]*w1+x_test[1]*w2+x_test[2]*w3+x_test[3]*w4+x_test[4]*w5+x_test[5]*w6+x_test[6]*w7

In [110]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

0.0001573975071064056

In [111]:
results=pd.DataFrame(W)

In [112]:
results.to_csv('LR_results', mode='a', index = False, header=None)