In [59]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
df=pd.read_excel("3.xlsx",header=None)

In [60]:
X=df[[65,63,64,73,70,74,71]].iloc[:][1:]

In [61]:
y=df[82].iloc[:][1:]

In [62]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 

In [63]:
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
x_train.columns=[0,1,2,3,4,5,6]
n=x_train.count()[0]
x_train.head()

0       1       2         3        4       5        6
0   11.58   10.11   10.11   1226.11    95.79   43.97   237.18
1    0.00    0.00    0.00      0.00     0.00    0.00     0.00
2  194.74  147.39  147.39  27868.39  1963.11  597.61  4585.63
3   82.89   73.76   73.76  20263.68  1177.21  154.74  2676.66
4   12.00   12.00   12.00   1212.00   110.00   62.00   270.00

In [64]:
sum_x1=0
sum_x2=0
sum_x3=0
sum_x4=0
sum_x5=0
sum_x6=0
sum_x7=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x1x3=0
sum_x1x4=0
sum_x1x5=0
sum_x1x6=0
sum_x1x7=0
sum_x2x2=0
sum_x2x3=0
sum_x2x4=0
sum_x2x5=0
sum_x2x6=0
sum_x2x7=0
sum_x3x3=0
sum_x3x4=0
sum_x3x5=0
sum_x3x6=0
sum_x3x7=0
sum_x4x4=0
sum_x4x5=0
sum_x4x6=0
sum_x4x7=0
sum_x5x5=0
sum_x5x6=0
sum_x5x7=0
sum_x6x6=0
sum_x6x7=0
sum_x7x7=0
sum_x1y1=0
sum_x2y1=0
sum_x3y1=0
sum_x4y1=0
sum_x5y1=0
sum_x6y1=0
sum_x7y1=0

for i in range(0,n):
    sum_x1=sum_x1+x_train[0][i]
    sum_x2=sum_x2+x_train[1][i]
    sum_x3=sum_x3+x_train[2][i]
    sum_x4=sum_x4+x_train[3][i]
    sum_x5=sum_x5+x_train[4][i]
    sum_x6=sum_x6+x_train[5][i]
    sum_x7=sum_x7+x_train[6][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train[0][i]*x_train[0][i]
    sum_x1x2=sum_x1x2+x_train[0][i]*x_train[1][i]
    sum_x1x3=sum_x1x3+x_train[0][i]*x_train[2][i]
    sum_x1x4=sum_x1x4+x_train[0][i]*x_train[3][i]
    sum_x1x5=sum_x1x5+x_train[0][i]*x_train[4][i]
    sum_x1x6=sum_x1x6+x_train[0][i]*x_train[5][i]
    sum_x1x7=sum_x1x7+x_train[0][i]*x_train[6][i]
    sum_x2x2=sum_x2x2+x_train[1][i]*x_train[1][i]
    sum_x2x3=sum_x2x3+x_train[1][i]*x_train[2][i]
    sum_x2x4=sum_x2x4+x_train[1][i]*x_train[3][i]
    sum_x2x5=sum_x2x5+x_train[1][i]*x_train[4][i]
    sum_x2x6=sum_x2x6+x_train[1][i]*x_train[5][i]
    sum_x2x7=sum_x2x7+x_train[1][i]*x_train[6][i]
    sum_x3x3=sum_x3x3+x_train[2][i]*x_train[2][i]
    sum_x3x4=sum_x3x4+x_train[2][i]*x_train[3][i]
    sum_x3x5=sum_x3x5+x_train[2][i]*x_train[4][i]
    sum_x3x6=sum_x3x6+x_train[2][i]*x_train[5][i]
    sum_x3x7=sum_x3x7+x_train[2][i]*x_train[6][i]
    sum_x4x4=sum_x4x4+x_train[3][i]*x_train[3][i]
    sum_x4x5=sum_x4x5+x_train[3][i]*x_train[4][i]
    sum_x4x6=sum_x4x6+x_train[3][i]*x_train[5][i]
    sum_x4x7=sum_x4x7+x_train[3][i]*x_train[6][i]
    sum_x5x5=sum_x5x5+x_train[4][i]*x_train[4][i]
    sum_x5x6=sum_x5x6+x_train[4][i]*x_train[5][i]
    sum_x5x7=sum_x5x7+x_train[4][i]*x_train[6][i]
    sum_x6x6=sum_x6x6+x_train[5][i]*x_train[5][i]
    sum_x6x7=sum_x6x7+x_train[5][i]*x_train[6][i]
    sum_x7x7=sum_x7x7+x_train[6][i]*x_train[6][i]
    sum_x1y1=sum_x1y1+x_train[0][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train[1][i]*y_train[i]
    sum_x3y1=sum_x3y1+x_train[2][i]*y_train[i]
    sum_x4y1=sum_x4y1+x_train[3][i]*y_train[i]
    sum_x5y1=sum_x5y1+x_train[4][i]*y_train[i]
    sum_x6y1=sum_x6y1+x_train[5][i]*y_train[i]
    sum_x7y1=sum_x7y1+x_train[6][i]*y_train[i]

In [65]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train, y_train)

In [66]:
reg.coef_

array([ 0.02731745, -0.00197948, -0.02009149,  0.00020507,  0.00544072,
        0.00462017, -0.00441387])

In [67]:
reg.intercept_

-0.047476623876914564

In [68]:
A = np.array([[n, sum_x1, sum_x2,sum_x3,sum_x4,sum_x5,sum_x6,sum_x7], 
              [sum_x1,sum_x1x1,sum_x1x2,sum_x1x3,sum_x1x4,sum_x1x5,sum_x1x6,sum_x1x7],
              [sum_x2,sum_x1x2,sum_x2x2,sum_x2x3,sum_x2x4,sum_x2x5,sum_x2x6,sum_x2x7],
              [sum_x3,sum_x1x3,sum_x2x3,sum_x3x3,sum_x3x4,sum_x3x5,sum_x3x6,sum_x3x7],
              [sum_x4,sum_x1x4,sum_x2x4,sum_x3x4,sum_x4x4,sum_x4x5,sum_x4x6,sum_x4x7],
              [sum_x5,sum_x1x5,sum_x2x5,sum_x3x5,sum_x4x5,sum_x5x5,sum_x5x6,sum_x5x7],
              [sum_x6,sum_x1x6,sum_x2x6,sum_x3x6,sum_x4x6,sum_x5x6,sum_x6x6,sum_x6x7],
              [sum_x7,sum_x1x7,sum_x2x7,sum_x3x7,sum_x4x7,sum_x5x7,sum_x6x7,sum_x7x7]])

In [69]:
B=np.array([sum_y1, sum_x1y1, sum_x2y1,sum_x3y1,sum_x4y1,sum_x5y1,sum_x6y1,sum_x7y1])

In [70]:
from numpy.linalg import inv
Inverse=inv(A)
Inverse

array([[ 1.03040751e-01,  1.00428082e-03,  5.37614815e-04,
        -1.28490485e-03, -1.43009924e-05,  1.57566959e-03,
        -1.10214419e-04, -6.08996034e-04],
       [ 1.00428082e-03,  1.64354291e-03, -1.09674829e-03,
        -4.18769855e-04,  2.21993692e-06,  6.67585251e-05,
         1.58840473e-05, -5.79566503e-05],
       [ 5.37614815e-04, -1.09674829e-03,  1.78767029e-03,
        -9.27372501e-04, -4.14649169e-07,  1.39221344e-04,
         9.75411340e-05, -5.66691854e-05],
       [-1.28490485e-03, -4.18769855e-04, -9.27372501e-04,
         2.31516218e-03, -2.89672953e-06, -1.56296875e-04,
        -2.31527023e-04,  8.58427887e-05],
       [-1.43009924e-05,  2.21993692e-06, -4.14649169e-07,
        -2.89672953e-06,  1.17066038e-07,  1.47051167e-08,
         1.98956542e-06, -9.39314588e-07],
       [ 1.57566959e-03,  6.67585251e-05,  1.39221344e-04,
        -1.56296875e-04,  1.47051167e-08,  1.72768287e-04,
         1.89085722e-05, -7.91071578e-05],
       [-1.10214419e-04,  1.588404

In [71]:
np.around(Inverse @ A).astype(int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [72]:
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]+Inverse[0][3]*B[3]+Inverse[0][4]*B[4]+Inverse[0][5]*B[5]+Inverse[0][6]*B[6]+Inverse[0][7]*B[7]

In [73]:
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]+Inverse[1][3]*B[3]+Inverse[1][4]*B[4]+Inverse[1][5]*B[5]+Inverse[1][6]*B[6]+Inverse[1][7]*B[7]

In [74]:
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]+Inverse[2][3]*B[3]+Inverse[2][4]*B[4]+Inverse[2][5]*B[5]+Inverse[2][6]*B[6]+Inverse[2][7]*B[7]

In [75]:
w3=Inverse[3][0]*B[0]+Inverse[3][1]*B[1]+Inverse[3][2]*B[2]+Inverse[3][3]*B[3]+Inverse[3][4]*B[4]+Inverse[3][5]*B[5]+Inverse[3][6]*B[6]+Inverse[3][7]*B[7]

In [76]:
w4=Inverse[4][0]*B[0]+Inverse[4][1]*B[1]+Inverse[4][2]*B[2]+Inverse[4][3]*B[3]+Inverse[4][4]*B[4]+Inverse[4][5]*B[5]+Inverse[4][6]*B[6]+Inverse[4][7]*B[7]

In [77]:
w5=Inverse[5][0]*B[0]+Inverse[5][1]*B[1]+Inverse[5][2]*B[2]+Inverse[5][3]*B[3]+Inverse[5][4]*B[4]+Inverse[5][5]*B[5]+Inverse[5][6]*B[6]+Inverse[5][7]*B[7]

In [78]:
w6=Inverse[6][0]*B[0]+Inverse[6][1]*B[1]+Inverse[6][2]*B[2]+Inverse[6][3]*B[3]+Inverse[6][4]*B[4]+Inverse[6][5]*B[5]+Inverse[6][6]*B[6]+Inverse[6][7]*B[7]

In [79]:
w7=Inverse[7][0]*B[0]+Inverse[7][1]*B[1]+Inverse[7][2]*B[2]+Inverse[7][3]*B[3]+Inverse[7][4]*B[4]+Inverse[7][5]*B[5]+Inverse[7][6]*B[6]+Inverse[7][7]*B[7]

In [80]:
W=np.array([w0,w1,w2,w3,w4,w5,w6,w7])

In [81]:
W

array([-0.04747662,  0.02731745, -0.00197948, -0.02009149,  0.00020507,
        0.00544072,  0.00462017, -0.00441387])

In [82]:
x_test.columns=[0,1,2,3,4,5,6]
x_test.head()

0       1       2         3        4       5        6
0    0.00    0.00    0.00      0.00     0.00    0.00     0.00
1    8.47    7.74    7.74    928.24    76.42   38.21   188.97
2  211.34  178.34  178.34  31647.24  2249.92  617.66  5249.71
3    8.79    8.05    8.05   1137.68    97.29   51.16   235.76
4  191.58  169.11  167.11  28986.11  2297.84  735.39  5325.13

In [83]:
y_pred=w0+x_test[0]*w1+x_test[1]*w2+x_test[2]*w3+x_test[3]*w4+x_test[4]*w5+x_test[5]*w6+x_test[6]*w7

In [84]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

0.20402992990545069

In [85]:
results=pd.DataFrame(W)

In [86]:
results.to_csv('LR_results', mode='a', index = False, header=None)