In [28]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
df=pd.read_excel("5.xlsx",header=None)

In [29]:
X=df[[78,3,34,4,79,35,38]].iloc[:][1:]

In [30]:
y=df[82].iloc[:][1:]

In [31]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 

In [32]:
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
x_train.columns=[0,1,2,3,4,5,6]
n=x_train.count()[0]
x_train.head()

0       1        2        3      4       5       6
0    0.00   10.00   142.00    57.00   0.00   10.00    0.00
1    0.00    5.00    19.00     5.00   0.00    5.00    0.00
2  240.05  363.75  2117.05  1294.30  67.85  331.45  630.95
3    0.00   25.00   486.00   197.00   0.00   25.00    0.00
4   71.05  160.40   839.35   487.75  21.45  160.40  268.55

In [33]:
sum_x1=0
sum_x2=0
sum_x3=0
sum_x4=0
sum_x5=0
sum_x6=0
sum_x7=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x1x3=0
sum_x1x4=0
sum_x1x5=0
sum_x1x6=0
sum_x1x7=0
sum_x2x2=0
sum_x2x3=0
sum_x2x4=0
sum_x2x5=0
sum_x2x6=0
sum_x2x7=0
sum_x3x3=0
sum_x3x4=0
sum_x3x5=0
sum_x3x6=0
sum_x3x7=0
sum_x4x4=0
sum_x4x5=0
sum_x4x6=0
sum_x4x7=0
sum_x5x5=0
sum_x5x6=0
sum_x5x7=0
sum_x6x6=0
sum_x6x7=0
sum_x7x7=0
sum_x1y1=0
sum_x2y1=0
sum_x3y1=0
sum_x4y1=0
sum_x5y1=0
sum_x6y1=0
sum_x7y1=0

for i in range(0,n):
    sum_x1=sum_x1+x_train[0][i]
    sum_x2=sum_x2+x_train[1][i]
    sum_x3=sum_x3+x_train[2][i]
    sum_x4=sum_x4+x_train[3][i]
    sum_x5=sum_x5+x_train[4][i]
    sum_x6=sum_x6+x_train[5][i]
    sum_x7=sum_x7+x_train[6][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train[0][i]*x_train[0][i]
    sum_x1x2=sum_x1x2+x_train[0][i]*x_train[1][i]
    sum_x1x3=sum_x1x3+x_train[0][i]*x_train[2][i]
    sum_x1x4=sum_x1x4+x_train[0][i]*x_train[3][i]
    sum_x1x5=sum_x1x5+x_train[0][i]*x_train[4][i]
    sum_x1x6=sum_x1x6+x_train[0][i]*x_train[5][i]
    sum_x1x7=sum_x1x7+x_train[0][i]*x_train[6][i]
    sum_x2x2=sum_x2x2+x_train[1][i]*x_train[1][i]
    sum_x2x3=sum_x2x3+x_train[1][i]*x_train[2][i]
    sum_x2x4=sum_x2x4+x_train[1][i]*x_train[3][i]
    sum_x2x5=sum_x2x5+x_train[1][i]*x_train[4][i]
    sum_x2x6=sum_x2x6+x_train[1][i]*x_train[5][i]
    sum_x2x7=sum_x2x7+x_train[1][i]*x_train[6][i]
    sum_x3x3=sum_x3x3+x_train[2][i]*x_train[2][i]
    sum_x3x4=sum_x3x4+x_train[2][i]*x_train[3][i]
    sum_x3x5=sum_x3x5+x_train[2][i]*x_train[4][i]
    sum_x3x6=sum_x3x6+x_train[2][i]*x_train[5][i]
    sum_x3x7=sum_x3x7+x_train[2][i]*x_train[6][i]
    sum_x4x4=sum_x4x4+x_train[3][i]*x_train[3][i]
    sum_x4x5=sum_x4x5+x_train[3][i]*x_train[4][i]
    sum_x4x6=sum_x4x6+x_train[3][i]*x_train[5][i]
    sum_x4x7=sum_x4x7+x_train[3][i]*x_train[6][i]
    sum_x5x5=sum_x5x5+x_train[4][i]*x_train[4][i]
    sum_x5x6=sum_x5x6+x_train[4][i]*x_train[5][i]
    sum_x5x7=sum_x5x7+x_train[4][i]*x_train[6][i]
    sum_x6x6=sum_x6x6+x_train[5][i]*x_train[5][i]
    sum_x6x7=sum_x6x7+x_train[5][i]*x_train[6][i]
    sum_x7x7=sum_x7x7+x_train[6][i]*x_train[6][i]
    sum_x1y1=sum_x1y1+x_train[0][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train[1][i]*y_train[i]
    sum_x3y1=sum_x3y1+x_train[2][i]*y_train[i]
    sum_x4y1=sum_x4y1+x_train[3][i]*y_train[i]
    sum_x5y1=sum_x5y1+x_train[4][i]*y_train[i]
    sum_x6y1=sum_x6y1+x_train[5][i]*y_train[i]
    sum_x7y1=sum_x7y1+x_train[6][i]*y_train[i]

In [34]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train, y_train)

In [35]:
reg.coef_

array([ 0.00113717,  0.0014744 ,  0.00035813, -0.00060783,  0.00126464,
       -0.00278761,  0.00063987])

In [36]:
reg.intercept_

0.029904077215887948

In [37]:
A = np.array([[n, sum_x1, sum_x2,sum_x3,sum_x4,sum_x5,sum_x6,sum_x7], 
              [sum_x1,sum_x1x1,sum_x1x2,sum_x1x3,sum_x1x4,sum_x1x5,sum_x1x6,sum_x1x7],
              [sum_x2,sum_x1x2,sum_x2x2,sum_x2x3,sum_x2x4,sum_x2x5,sum_x2x6,sum_x2x7],
              [sum_x3,sum_x1x3,sum_x2x3,sum_x3x3,sum_x3x4,sum_x3x5,sum_x3x6,sum_x3x7],
              [sum_x4,sum_x1x4,sum_x2x4,sum_x3x4,sum_x4x4,sum_x4x5,sum_x4x6,sum_x4x7],
              [sum_x5,sum_x1x5,sum_x2x5,sum_x3x5,sum_x4x5,sum_x5x5,sum_x5x6,sum_x5x7],
              [sum_x6,sum_x1x6,sum_x2x6,sum_x3x6,sum_x4x6,sum_x5x6,sum_x6x6,sum_x6x7],
              [sum_x7,sum_x1x7,sum_x2x7,sum_x3x7,sum_x4x7,sum_x5x7,sum_x6x7,sum_x7x7]])

In [38]:
B=np.array([sum_y1, sum_x1y1, sum_x2y1,sum_x3y1,sum_x4y1,sum_x5y1,sum_x6y1,sum_x7y1])

In [39]:
from numpy.linalg import inv
Inverse=inv(A)
Inverse

array([[ 6.70314745e-03, -1.41767476e-05,  4.54524194e-05,
        -9.14811892e-06, -3.78958452e-06,  2.04213066e-05,
        -4.74286908e-05,  2.97856531e-05],
       [-1.41767476e-05,  6.53978678e-06, -1.79769989e-06,
         1.92043326e-08,  8.58107143e-08, -1.85204297e-05,
         2.53646927e-06, -6.28075183e-07],
       [ 4.54524194e-05, -1.79769989e-06,  6.53092000e-06,
         2.22781314e-07, -1.17010311e-06,  5.05651395e-06,
        -6.67223147e-06,  1.36774751e-06],
       [-9.14811892e-06,  1.92043326e-08,  2.22781314e-07,
         3.49054952e-07, -5.37546617e-07,  6.07633182e-07,
        -8.97813057e-07,  2.70185864e-07],
       [-3.78958452e-06,  8.58107143e-08, -1.17010311e-06,
        -5.37546617e-07,  1.05490298e-06, -1.13371545e-06,
         2.05203230e-06, -7.19121568e-07],
       [ 2.04213066e-05, -1.85204297e-05,  5.05651395e-06,
         6.07633182e-07, -1.13371545e-06,  6.69100726e-05,
        -1.09928764e-05,  2.68496778e-06],
       [-4.74286908e-05,  2.536469

In [40]:
np.around(Inverse @ A).astype(int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [41]:
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]+Inverse[0][3]*B[3]+Inverse[0][4]*B[4]+Inverse[0][5]*B[5]+Inverse[0][6]*B[6]+Inverse[0][7]*B[7]

In [42]:
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]+Inverse[1][3]*B[3]+Inverse[1][4]*B[4]+Inverse[1][5]*B[5]+Inverse[1][6]*B[6]+Inverse[1][7]*B[7]

In [43]:
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]+Inverse[2][3]*B[3]+Inverse[2][4]*B[4]+Inverse[2][5]*B[5]+Inverse[2][6]*B[6]+Inverse[2][7]*B[7]

In [44]:
w3=Inverse[3][0]*B[0]+Inverse[3][1]*B[1]+Inverse[3][2]*B[2]+Inverse[3][3]*B[3]+Inverse[3][4]*B[4]+Inverse[3][5]*B[5]+Inverse[3][6]*B[6]+Inverse[3][7]*B[7]

In [45]:
w4=Inverse[4][0]*B[0]+Inverse[4][1]*B[1]+Inverse[4][2]*B[2]+Inverse[4][3]*B[3]+Inverse[4][4]*B[4]+Inverse[4][5]*B[5]+Inverse[4][6]*B[6]+Inverse[4][7]*B[7]

In [46]:
w5=Inverse[5][0]*B[0]+Inverse[5][1]*B[1]+Inverse[5][2]*B[2]+Inverse[5][3]*B[3]+Inverse[5][4]*B[4]+Inverse[5][5]*B[5]+Inverse[5][6]*B[6]+Inverse[5][7]*B[7]

In [47]:
w6=Inverse[6][0]*B[0]+Inverse[6][1]*B[1]+Inverse[6][2]*B[2]+Inverse[6][3]*B[3]+Inverse[6][4]*B[4]+Inverse[6][5]*B[5]+Inverse[6][6]*B[6]+Inverse[6][7]*B[7]

In [48]:
w7=Inverse[7][0]*B[0]+Inverse[7][1]*B[1]+Inverse[7][2]*B[2]+Inverse[7][3]*B[3]+Inverse[7][4]*B[4]+Inverse[7][5]*B[5]+Inverse[7][6]*B[6]+Inverse[7][7]*B[7]

In [49]:
W=np.array([w0,w1,w2,w3,w4,w5,w6,w7])

In [50]:
W

array([ 0.02990408,  0.00113717,  0.0014744 ,  0.00035813, -0.00060783,
        0.00126464, -0.00278761,  0.00063987])

In [51]:
x_test.columns=[0,1,2,3,4,5,6]
x_test.head()

0     1      2      3    4     5     6
0  35.0  76.0  308.0  186.0  6.0  76.0  92.0
1   0.0  17.0  406.4  178.0  0.0  17.0   0.0
2  10.0  11.0   79.0   38.0  3.0  11.0  16.0
3   0.0   7.0   45.0   27.0  0.0   7.0   0.0
4   0.0  11.0  234.0  198.0  0.0  11.0   0.0

In [52]:
y_pred=w0+x_test[0]*w1+x_test[1]*w2+x_test[2]*w3+x_test[3]*w4+x_test[4]*w5+x_test[5]*w6+x_test[6]*w7

In [53]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

0.05574657844737738

In [54]:
results=pd.DataFrame(W)

In [55]:
results.to_csv('LR_results', mode='a', index = False, header=None)