In [29]:
import pandas as pd 
import numpy as np
from sklearn import preprocessing
df=pd.read_excel("7.xlsx",header=None)

In [30]:
X=df[[67,72,68,74,35,3,4]].iloc[:][1:]

In [31]:
y=df[82].iloc[:][1:]

In [32]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) 

In [33]:
x_train.reset_index(inplace = True, drop = True) 
x_test.reset_index(inplace = True, drop = True) 
y_train.reset_index(inplace = True, drop = True) 
y_test.reset_index(inplace = True, drop = True) 
x_train.columns=[0,1,2,3,4,5,6]
n=x_train.count()[0]
x_train.head()

0        1        2        3       4       5        6
0    53.00   156.43   103.43    70.00    8.00    9.00   156.00
1   155.00   365.79   210.79   114.11   40.00   40.00   136.29
2   267.64   876.68   609.04   279.82  104.04  107.04   720.89
3  1052.61  3455.86  2403.25  1145.11  391.00  392.00  2802.29
4   661.75  1042.18   380.43   326.18  288.18  315.75  1498.57

In [34]:
sum_x1=0
sum_x2=0
sum_x3=0
sum_x4=0
sum_x5=0
sum_x6=0
sum_x7=0
sum_y1=0
sum_x1x1=0
sum_x1x2=0
sum_x1x3=0
sum_x1x4=0
sum_x1x5=0
sum_x1x6=0
sum_x1x7=0
sum_x2x2=0
sum_x2x3=0
sum_x2x4=0
sum_x2x5=0
sum_x2x6=0
sum_x2x7=0
sum_x3x3=0
sum_x3x4=0
sum_x3x5=0
sum_x3x6=0
sum_x3x7=0
sum_x4x4=0
sum_x4x5=0
sum_x4x6=0
sum_x4x7=0
sum_x5x5=0
sum_x5x6=0
sum_x5x7=0
sum_x6x6=0
sum_x6x7=0
sum_x7x7=0
sum_x1y1=0
sum_x2y1=0
sum_x3y1=0
sum_x4y1=0
sum_x5y1=0
sum_x6y1=0
sum_x7y1=0

for i in range(0,n):
    sum_x1=sum_x1+x_train[0][i]
    sum_x2=sum_x2+x_train[1][i]
    sum_x3=sum_x3+x_train[2][i]
    sum_x4=sum_x4+x_train[3][i]
    sum_x5=sum_x5+x_train[4][i]
    sum_x6=sum_x6+x_train[5][i]
    sum_x7=sum_x7+x_train[6][i]
    sum_y1=sum_y1+y_train[i]
    sum_x1x1=sum_x1x1+x_train[0][i]*x_train[0][i]
    sum_x1x2=sum_x1x2+x_train[0][i]*x_train[1][i]
    sum_x1x3=sum_x1x3+x_train[0][i]*x_train[2][i]
    sum_x1x4=sum_x1x4+x_train[0][i]*x_train[3][i]
    sum_x1x5=sum_x1x5+x_train[0][i]*x_train[4][i]
    sum_x1x6=sum_x1x6+x_train[0][i]*x_train[5][i]
    sum_x1x7=sum_x1x7+x_train[0][i]*x_train[6][i]
    sum_x2x2=sum_x2x2+x_train[1][i]*x_train[1][i]
    sum_x2x3=sum_x2x3+x_train[1][i]*x_train[2][i]
    sum_x2x4=sum_x2x4+x_train[1][i]*x_train[3][i]
    sum_x2x5=sum_x2x5+x_train[1][i]*x_train[4][i]
    sum_x2x6=sum_x2x6+x_train[1][i]*x_train[5][i]
    sum_x2x7=sum_x2x7+x_train[1][i]*x_train[6][i]
    sum_x3x3=sum_x3x3+x_train[2][i]*x_train[2][i]
    sum_x3x4=sum_x3x4+x_train[2][i]*x_train[3][i]
    sum_x3x5=sum_x3x5+x_train[2][i]*x_train[4][i]
    sum_x3x6=sum_x3x6+x_train[2][i]*x_train[5][i]
    sum_x3x7=sum_x3x7+x_train[2][i]*x_train[6][i]
    sum_x4x4=sum_x4x4+x_train[3][i]*x_train[3][i]
    sum_x4x5=sum_x4x5+x_train[3][i]*x_train[4][i]
    sum_x4x6=sum_x4x6+x_train[3][i]*x_train[5][i]
    sum_x4x7=sum_x4x7+x_train[3][i]*x_train[6][i]
    sum_x5x5=sum_x5x5+x_train[4][i]*x_train[4][i]
    sum_x5x6=sum_x5x6+x_train[4][i]*x_train[5][i]
    sum_x5x7=sum_x5x7+x_train[4][i]*x_train[6][i]
    sum_x6x6=sum_x6x6+x_train[5][i]*x_train[5][i]
    sum_x6x7=sum_x6x7+x_train[5][i]*x_train[6][i]
    sum_x7x7=sum_x7x7+x_train[6][i]*x_train[6][i]
    sum_x1y1=sum_x1y1+x_train[0][i]*y_train[i]
    sum_x2y1=sum_x2y1+x_train[1][i]*y_train[i]
    sum_x3y1=sum_x3y1+x_train[2][i]*y_train[i]
    sum_x4y1=sum_x4y1+x_train[3][i]*y_train[i]
    sum_x5y1=sum_x5y1+x_train[4][i]*y_train[i]
    sum_x6y1=sum_x6y1+x_train[5][i]*y_train[i]
    sum_x7y1=sum_x7y1+x_train[6][i]*y_train[i]

In [35]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(x_train, y_train)

In [36]:
reg.coef_

array([-8.84446855e+00,  8.84851727e+00, -8.84737401e+00, -3.98317732e-03,
       -6.17170760e-03, -8.05008106e-04,  2.04383772e-04])

In [37]:
reg.intercept_

0.010368116742111771

In [38]:
A = np.array([[n, sum_x1, sum_x2,sum_x3,sum_x4,sum_x5,sum_x6,sum_x7], 
              [sum_x1,sum_x1x1,sum_x1x2,sum_x1x3,sum_x1x4,sum_x1x5,sum_x1x6,sum_x1x7],
              [sum_x2,sum_x1x2,sum_x2x2,sum_x2x3,sum_x2x4,sum_x2x5,sum_x2x6,sum_x2x7],
              [sum_x3,sum_x1x3,sum_x2x3,sum_x3x3,sum_x3x4,sum_x3x5,sum_x3x6,sum_x3x7],
              [sum_x4,sum_x1x4,sum_x2x4,sum_x3x4,sum_x4x4,sum_x4x5,sum_x4x6,sum_x4x7],
              [sum_x5,sum_x1x5,sum_x2x5,sum_x3x5,sum_x4x5,sum_x5x5,sum_x5x6,sum_x5x7],
              [sum_x6,sum_x1x6,sum_x2x6,sum_x3x6,sum_x4x6,sum_x5x6,sum_x6x6,sum_x6x7],
              [sum_x7,sum_x1x7,sum_x2x7,sum_x3x7,sum_x4x7,sum_x5x7,sum_x6x7,sum_x7x7]])

In [39]:
B=np.array([sum_y1, sum_x1y1, sum_x2y1,sum_x3y1,sum_x4y1,sum_x5y1,sum_x6y1,sum_x7y1])

In [40]:
from numpy.linalg import inv
Inverse=inv(A)
Inverse

array([[ 9.17492929e-02, -7.70009187e+00,  7.70017322e+00,
        -7.70005543e+00, -1.96663861e-04, -9.25468816e-05,
         3.62993012e-05, -7.97571148e-05],
       [-7.70009187e+00,  5.88060087e+03, -5.88064910e+03,
         5.88063312e+03,  7.70890034e-02, -1.55256678e-02,
         7.18617542e-02, -5.74344596e-03],
       [ 7.70017322e+00, -5.88064910e+03,  5.88069739e+03,
        -5.88068139e+03, -7.71363479e-02,  1.54304236e-02,
        -7.18957117e-02,  5.75049536e-03],
       [-7.70005543e+00,  5.88063312e+03, -5.88068139e+03,
         5.88066540e+03,  7.71252344e-02, -1.54452116e-02,
         7.18924574e-02, -5.74988501e-03],
       [-1.96663861e-04,  7.70890035e-02, -7.71363480e-02,
         7.71252345e-02,  4.96536480e-05,  6.40816300e-05,
         3.19284076e-05, -6.24101447e-06],
       [-9.25468818e-05, -1.55256677e-02,  1.54304235e-02,
        -1.54452115e-02,  6.40816300e-05,  2.02530214e-04,
         2.70884542e-05, -8.51256882e-06],
       [ 3.62993011e-05,  7.186175

In [41]:
np.around(Inverse @ A).astype(int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [42]:
w0=Inverse[0][0]*B[0]+Inverse[0][1]*B[1]+Inverse[0][2]*B[2]+Inverse[0][3]*B[3]+Inverse[0][4]*B[4]+Inverse[0][5]*B[5]+Inverse[0][6]*B[6]+Inverse[0][7]*B[7]

In [43]:
w1=Inverse[1][0]*B[0]+Inverse[1][1]*B[1]+Inverse[1][2]*B[2]+Inverse[1][3]*B[3]+Inverse[1][4]*B[4]+Inverse[1][5]*B[5]+Inverse[1][6]*B[6]+Inverse[1][7]*B[7]

In [44]:
w2=Inverse[2][0]*B[0]+Inverse[2][1]*B[1]+Inverse[2][2]*B[2]+Inverse[2][3]*B[3]+Inverse[2][4]*B[4]+Inverse[2][5]*B[5]+Inverse[2][6]*B[6]+Inverse[2][7]*B[7]

In [45]:
w3=Inverse[3][0]*B[0]+Inverse[3][1]*B[1]+Inverse[3][2]*B[2]+Inverse[3][3]*B[3]+Inverse[3][4]*B[4]+Inverse[3][5]*B[5]+Inverse[3][6]*B[6]+Inverse[3][7]*B[7]

In [46]:
w4=Inverse[4][0]*B[0]+Inverse[4][1]*B[1]+Inverse[4][2]*B[2]+Inverse[4][3]*B[3]+Inverse[4][4]*B[4]+Inverse[4][5]*B[5]+Inverse[4][6]*B[6]+Inverse[4][7]*B[7]

In [47]:
w5=Inverse[5][0]*B[0]+Inverse[5][1]*B[1]+Inverse[5][2]*B[2]+Inverse[5][3]*B[3]+Inverse[5][4]*B[4]+Inverse[5][5]*B[5]+Inverse[5][6]*B[6]+Inverse[5][7]*B[7]

In [48]:
w6=Inverse[6][0]*B[0]+Inverse[6][1]*B[1]+Inverse[6][2]*B[2]+Inverse[6][3]*B[3]+Inverse[6][4]*B[4]+Inverse[6][5]*B[5]+Inverse[6][6]*B[6]+Inverse[6][7]*B[7]

In [49]:
w7=Inverse[7][0]*B[0]+Inverse[7][1]*B[1]+Inverse[7][2]*B[2]+Inverse[7][3]*B[3]+Inverse[7][4]*B[4]+Inverse[7][5]*B[5]+Inverse[7][6]*B[6]+Inverse[7][7]*B[7]

In [50]:
W=np.array([w0,w1,w2,w3,w4,w5,w6,w7])

In [51]:
W

array([ 1.03652082e-02, -8.84526311e+00,  8.84931184e+00, -8.84816856e+00,
       -3.98318774e-03, -6.17170551e-03, -8.05017820e-04,  2.04384549e-04])

In [52]:
x_test.columns=[0,1,2,3,4,5,6]
x_test.head()

0        1        2        3       4        5        6
0     0.00     0.00     0.00     0.00   30.00    30.00    92.36
1  1428.75  3977.68  2548.93  1447.86  584.61  1034.75  5979.71
2    87.00   206.00   119.00    72.14   15.00    15.00   112.86
3    30.25    69.75    39.50    24.00    6.75     6.75    41.50
4    14.00    25.00    11.00     8.00   17.00    17.00    45.00

In [53]:
y_pred=w0+x_test[0]*w1+x_test[1]*w2+x_test[2]*w3+x_test[3]*w4+x_test[4]*w5+x_test[5]*w6+x_test[6]*w7

In [54]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

0.22359136943741675

In [55]:
results=pd.DataFrame(W)

In [56]:
results.to_csv('LR_results', mode='a', index = False, header=None)